spring:
  application:
    name: nn-currency-account
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
server:
  error:
    include-message: always
nbp:
  exchange-rate:
    url.usd: https://api.nbp.pl/api/exchangerates/rates/a/usd/?format=json
